name = "gokarts-multiplayer"
main = "cloudflare-worker.js"
compatibility_date = "2023-12-01"

[durable_objects]
bindings = [
  { name = "GAME_ROOMS", class_name = "GameRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["GameRoom"]

[env.production]
name = "gokarts-multiplayer-prod"

[env.staging]
name = "gokarts-multiplayer-staging"