name = "gokarts-multiplayer"
main = "cloudflare-worker.js"
compatibility_date = "2023-12-01"

[durable_objects]
bindings = [
  { name = "MATCHMAKER", class_name = "MatchmakerDO" },
  { name = "ROOM_REGISTRY", class_name = "RoomRegistryDO" },
  { name = "ROOM_DO", class_name = "RoomDO" },
  { name = "LEADERBOARD", class_name = "LeaderboardDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["MatchmakerDO", "RoomRegistryDO", "RoomDO"]

[[migrations]]
tag = "v2"
new_classes = ["LeaderboardDO"]

[vars]
ROOM_SIZE = "5"
ALLOWED_ORIGINS = "https://go-karts.vercel.app,https://*.vercel.app,https://grokkarts.online,https://gokarts.online"
QUEUE_TTL_MS = "20000"
ROOM_HEARTBEAT_MS = "30000"

[env.dev]
name = "gokarts-multiplayer-dev"
[env.dev.vars]
ROOM_SIZE = "2"

[env.production]
name = "gokarts-multiplayer-prod"
[env.production.durable_objects]
bindings = [
  { name = "MATCHMAKER", class_name = "MatchmakerDO" },
  { name = "ROOM_REGISTRY", class_name = "RoomRegistryDO" },
  { name = "ROOM_DO", class_name = "RoomDO" },
  { name = "LEADERBOARD", class_name = "LeaderboardDO" }
]
[env.production.vars]
ROOM_SIZE = "5"
ALLOWED_ORIGINS = "https://go-karts.vercel.app,https://*.vercel.app,https://grokkarts.online,https://gokarts.online"
QUEUE_TTL_MS = "20000"
ROOM_HEARTBEAT_MS = "30000"
ENVIRONMENT = "production"

[env.staging]
name = "gokarts-multiplayer-staging"